### ISSUE TITLE
Encrypt and Decrypt methods accept "data: string, address: string" as params not (account, data)

### ISSUE THREAD

**Issue by tomasmcm** [polybase/docs#25]
The issue is in this page: https://github.com/polybase/docs/blob/main/write-data.mdx#using-wallet-through-an-extension-1

The code example in the docs website shows how to encrypt data with
```js
const encryptedValue = await eth.encrypt(account, "top secret info");
```
But that throws an error, because the order of the parameters is switched. According to the source https://github.com/polybase/polybase-ts/blob/main/packages/eth/src/eth.ts#L27 it should be:
```js
const encryptedValue = await eth.encrypt("top secret info", account);
```
The example for decrypt should also be updated:
```js
const decryptedValue = await eth.decrypt(encryptedValue, account);
```

**Comment by calummoore** [comment]
Thanks for highlighting this, we've pushed a fix for to docs 👍
